language: java
before_script:
- ant resolve
script:
- ant dist
deploy:
  provider: releases
  api_key:
    secure: SrOJ0fmha6fAYLuJhUXL/KG5zLmNkCHqknvfqpUbQNoPeJsELLzIA/UWfddIY/6WTkV2a/1MG2PLbFmBmpMCVU0sjg/kC/yf9a8tWOtAaH4VuL1uMm4EYIDKU7eUyV3LI57JIQu8b4zKSxA7B+i3pABrjdDSlm+TpUm+x5ryqWw=
  file: dist/cte-TRUNK-SNAPSHOT.zip
  on:
    repo: pedrofvteixeira/cte
